# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rspec", "3.10"
gem "httparty", "0.18.1"
gem "mongo", "2.13.1"
